WIP - Support Tape-shielded cables
opusonesolutions/carsons pull request #37
Opened 2019-10-29 04:07 UTC by EmilyYLMa

- [ ] Fix resistance calculation of tape-shield
- [ ] Test with IEEE13 tape-shielded cable
- [ ] Update README

2022-10-11 14:07 UTC, andace commented
**The four issues below are fixed**:
- Test with IEEE13 tape-shielded cable
    - An example of a tape shield cable from the IEEE13 test network is added 
- Update README
- Make tape shield resistivity configurable
    - Resistance calculation updated according to the formula R = copper_resistivity_20C/(cross-sectional area of tape shield conductor)
- Fix resistance calculation of tape-shield
    - The tape shield resistance calculation was validated with the IEEE13 tape shield cable example. The previous example from the Kersting gives a slightly different resistance for the tape shield; this is assumed to be a typo in the textbook example since the IEEE13 calculation matches the published results when using the implemented formula. The Kersting test case is updated slightly from the published result to account for the numerical error in the example.

2022-10-12 15:08 UTC, AnjoMan requested changes

2022-10-12 15:08 UTC, AnjoMan commented on carsons/carsons.py
> +        self.tape_shield_phases = model.tape_shield_outer_diameter.keys()
i noticed you are assigning these but then the only thing they are used for is to pass into methods you call in the constructor. i wonder if we should access them inside those methods? or maybe we don't need them to become class attributes, just pass them from `model` into the methods

2022-10-12 15:08 UTC, AnjoMan commented on carsons/carsons.py
> +        return self.ρ_tape_shield/area
```suggestion
    @classmethod
    def compute_shield_r(cls, ds, thickness) -> float:
        area = (π*(ds/2)**2) - (π*(ds/2 - thickness)**2)
        return cls.ρ_tape_shield/area
```

2022-10-14 16:03 UTC, AnjoMan approved these changes

2022-10-14 16:07 UTC, merged