CI updates
opusonesolutions/carsons pull request #44
Opened 2023-01-18 20:40 UTC by AnjoMan

* new versions of python have come out, we should test against them
* pyproject.toml is now a standard, we should use it

2023-01-19 16:37 UTC, andace commented
@AnjoMan have you thought of using black and adding it to the pre-commit hooks?

2023-01-19 18:24 UTC, veronicaguo approved these changes
LGTM!

2023-01-19 22:25 UTC, andace requested changes

2023-01-19 22:25 UTC, andace commented on .github/workflows/python-package.yaml
>      - uses: actions/checkout@v2
Should we use checkout@v3?

2023-01-20 19:58 UTC, AnjoMan commented on .github/workflows/python-package.yaml
>      - uses: actions/checkout@v2
Good thinking! fixed

2023-01-20 19:59 UTC, AnjoMan commented
> @AnjoMan have you thought of using black and adding it to the pre-commit hooks?

I have added black to the CI. i did add a bunch of disables, because black is not really optimized around matrix readibility and there are a lot of matrixes in the code.

2023-01-20 20:15 UTC, andace approved these changes

2023-01-20 21:15 UTC, merged